name: kencan
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  appinio_swiper: ^1.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.3.1
  country_list_pick: ^1.0.1+5
  cupertino_icons: ^1.0.5
  dotted_decoration: ^2.0.0
  easy_localization: ^3.0.0
  file_picker: ^5.2.4
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.9
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_login_facebook: ^1.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.1.2
  google_sign_in: ^5.0.7
  http: ^0.13.3
  outline_gradient_button: ^2.0.0+1
  pin_code_fields: ^7.3.0
  provider: ^6.0.5
  rename: ^2.0.1
  rounded_tabbar_widget: ^0.0.2
  smooth_page_indicator: ^1.0.0+2
  stylish_bottom_bar: ^0.1.3
  swipe_cards: ^1.0.0
  swipeable_card_stack: ^0.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  
  image_path_ios: "assets/images/kencanLogoIOS.png"
  image_path_android: "assets/images/DABOO.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansProSemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansProRegular.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: assets/fonts/PacificoRegular.ttf
          weight: 400
